### ISSUE TITLE
[Spike] Research into software architecture.

### ISSUE THREAD

**Issue by mohammedri** [uwblueprint/help-lesotho#1]

**Comment by rperryng** [comment]
Here's a compiled list of the topics / ideas I think we should implement on our site
- SVGs instead of images, or at the very least compress them (https://tinypng.com/)
- Barebones/No front end libraries (Preact, JQueryLite) for main side of website
- Minification/Uglifcation of scripts/css
- Using Gzip compression for our HTML

Overall these items will have the highest impact on lowering the bandwidth usage for consumers (there are other techniques we can use to reduce the bandwidth usage on our side, such as using CDN's for static file hosting, but with our estimated website traffic this is likely overkill)

As for structure of the app, there is nothing too far from a standard MVC rails app that we would deviate from.  The only overall large architectural decision would be how to implement an admin facing side of the website, which doesn't have the same bandwidth constraints as the main site.

We can keep the admin side of the site and the main side of the site in a single rails app by forwarding all `/admin` requests to an admin controller, which can perform authentication checks, and use a vastly different template for rendering.  But ideally all admin parts of the website would fall under the `/admin` path of the website.  This also means we would generate different front end assets for the main and admin parts of the site, which can be facilitated easily using the Rails pipeline or any other front-end build tool, e.g. `Grunt`, `gulpjs`, `broccolijs`, etc.

We can't go into more detail of the structure until we have a better vision of specific interactions and pages for the sites.  Once we have these we can meet and have a design session on what kind of models we'll have and have some logic as to how the forum will be structured/rendered

**Comment by chrisjluc** [comment]
I don't know if you've done this yet, but you can consider talking to @aaronte directly! He's done a lot of work in optimizing webpages for low bandwidth, so he probably has some useful insights for you guys.

**Comment by rperryng** [comment]
Another thing: We'll likely want to turn off Turbolinks and [JQuery UJS](https://robots.thoughtbot.com/a-tour-of-rails-jquery-ujs), which are used under the hood and by default in new rails app.  By taking these out we remove about 100kb (minified) from all page loads.

UJS is used internally by rails so by removing it, some aspects of the application will have to be written differently that normal (syntactically).  The following blog post goes over this quite well https://www.viget.com/articles/delete-in-rails-without-jquery-and-ujs

**Comment by mohammedri** [comment]
Putting further research back to the backlog on hold for this sprint. So that we can optimize as we go. 
Rails is the backend we will be using. Seems like there are a ton of optimizations we can do there.

**Comment by gautamgupta** [comment]
From https://docs.google.com/document/d/1YnmXxwquOfroTrEYDmcrwD7eFtkKLb5aFX90_Srf0u8/edit:

1. Site structure has to be conducive to low bandwidth: 
    1. Put useful items at top of page, they are loaded first 
    2. Have search, site map so people don’t have to load many pages to find what they’re looking for 

2. Allow text-only interaction. This may entail 
    1. creating and use of a text-only theme (and the ability for user to choose the one they prefer), 
    2. publishing of a number of RSS feeds, so that user can receive a text-only version of the new content on your website 
    3. subscribing to receive plain text emails whenever new content of interest is created on the website 
    4. granting to the user the possibility to post new content using emails. 

3. Images 
    1. CSS sprites? 
    2. Css for everything other than icons 
    3. Tune me uses images, i think we can get away with that by just having &lt;5 on the page (stories) 

4. Bottom line is reduce page size 
    1. Tuneme is 313kb, we can cut that a lot 

  

General site structure:
 - Stories
 - Articles
 - Info (help lesotho, clinics)
 - Forum
