### ISSUE TITLE
Querying for trending posts

### ISSUE THREAD

**Issue by gautamgupta** [uwblueprint/help-lesotho#25]
- [ ] Figure out a good logic based on recency, # comments, # likes
 - [ ] Add a method to query for a number of posts based on this logic

**Comment by ajyang99** [comment]
This is the formula used by reddit:
https://medium.com/hacking-and-gonzo/how-reddit-ranking-algorithms-work-ef111e33d0d9

Since we don't have downvotes, the formula for us should be:
log_10 z + y * (submission time - epoch)/45000,
where z = max{1, number of likes}, epoch is 1970/1/1/, the time difference is in seconds, and y = 0 if there are no likes and 1 otherwise.

This is hackernews:
https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d
